name: fairness-in-ml
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - ipython
  - jedi
  - jupyter
  - tensorflow
  - matplotlib
  - notebook
  - pandas
  - pip
  - python=3
  - scikit-learn
  - seaborn
  - pytorch
